# Generated by Django 5.1.5 on 2025-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ImageField(default='', upload_to='reviewer/profile/'),
        ),
    ]
