# Generated by Django 5.1.5 on 2025-01-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
