# Generated by Django 5.1.5 on 2025-01-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category/image/'),
        ),
    ]
