# Generated by Django 5.1.5 on 2025-01-25 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.ImageField(default='', upload_to='reviewer/profile/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
