# Generated by Django 5.1.5 on 2025-01-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0002_review_profile'),
        ('techno', '0003_review'),
    ]

    operations = [
    ]
