# Generated by Django 5.1.5 on 2025-01-21 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0003_addcategory_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='Addcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techno.addcategory'),
        ),
    ]
