# Generated by Django 5.1.5 on 2025-01-25 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0004_merge_0002_review_profile_0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='techno.product'),
        ),
    ]
