# Generated by Django 5.1.5 on 2025-01-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0004_alter_advertisement_addcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
