# Generated by Django 5.1.5 on 2025-01-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0006_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(default=''),
        ),
    ]
