# Generated by Django 5.1.5 on 2025-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techno', '0010_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
